# Generated by Django 6.0.7 on 2026-07-27 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['type', 'name']},
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='company',
            new_name='type',
        ),
    ]
