# Generated by Django 6.0.7 on 2026-07-28 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('booking', '0003_booking_payment_id_booking_payment_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingseat',
            name='traveller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.mytraveller'),
        ),
    ]
