# Generated by Django 6.0.7 on 2026-07-27 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts',  '0001_initial'),
        ('booking', '0001_initial'),
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritetrip',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='favoritetrip',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')]),
        ),
        migrations.AddIndex(
            model_name='travelhistory',
            index=models.Index(fields=['profile', 'viewed_at'], name='travel_trav_profile_84b031_idx'),
        ),
        migrations.AddConstraint(
            model_name='favoritetrip',
            constraint=models.UniqueConstraint(fields=('profile', 'trip'), name='unique_favorite_trip'),
        ),
    ]
